questionnaire = [
    ("du Togo ?", ("Lomé", "Lagos", "Accra", "Abidjan", "Niamey"), "Lomé"),
    ("du Ghana ?", ("Faso", "Libreville", "Accra", "Niamey"), "Accra"),
    ("de l'Afrique du sud ?", ("Pretoria", "Libreville", "Alger", "Gaborone"), "Pretoria"),
    ("de l'Algérie ?", ("Bujumbura", "Alger", "Gaborone"), "Alger"),
    ("de l'Angola ?", ("Lomé", "Luanda", "Lagos", "Porto-Novo"), "Luanda"),
    ("du Bénin ?", ("Porto-Novo", "Libreville", "Accra", "Conakry"), "Porto-Novo"),
    ("de la Gambie ?", ("Malabo", "Abuja", "Accra", "Banjul"), "Banjul"),
    ("de l'Éthiopie ?", ("Asmara", "Addis-Abeba", "Djibouti"), "Addis-Abeba"),
    ("de Djibouti ?", ("Djibouti", "Le Caire"), "Djibouti"),
    ("du Niger ?", ("Port-Louis", "Rabat", "Maputo", "Niamey"), "Niamey"),
    ("du Maroc ?", ("Rabat", "Windhoek", "Nouakchott", "Djouba", "Victoria", "Dakar"), "Rabat"),
    ("du Zimbabwe ?", ("Ouagadougou", "Harare", "Freetown"), "Harare"),
    ("du Tchad ?", ("N’Djamena", "Mogadisco", "Le Caire", "Khartoun"), "N’Djamena"),
    ("du Mali ?", ("Ouagadougou", "Mogadisco", "Dakar", "Bamako"), "Bamako"),
    ("de la République centrafricaine ?", ("Ouagadougou", "Bangui", "Bamako", "Khartoun"), "Bangui"),
    ("du Cameroun ?", ("Douala", "Rabat", "Accra"), "Douala"),
    ("de l'Égypte ?", ("Le Caire", "Mogadisco", "Freetown", "Khartoun"), "Le Caire"),
    ("du Burundi ?", ("Ouagadougou", "Bujumbura", "Conakry", "Lomé"), "Bujumbura"),
    ("du Nigéria ?", ("Niamey", "Kigali", "Abuja", "Brazaville"), "Abuja"),
    ("du Ouganda ?", ("Yaoundé", "Moroni", "Praia", "Kampala"), "Kampala"),
    ("du Burkina ?", ("Gitega", "Ouagadougou", "Abidjan", "Faso"), "Ouagadougou"),
    ("du Sierra Leone ?", ("Gitega", "Freetown", "Leone", "Lilongwe"), "Freetown"),
    ("du Gabon ?", ("Tripoli", "Tunis", "Sào Tomé", "Libreville"), "Libreville"),
    ("de la République Démocratique du Congo ?", ("Kinshassa", "Congo", "Brazaville", "Libreville"), "Kinshassa"),
    ("de la Côte d'ivoire ?", ("Niamey", "Yamoussokro", "Abuja", "Abidjan"), "Yamoussokro"),
    ("de la Guinée Équatoriale ?", ("Equateur", "Malabo", "Equatorial", "Brazaville"), "Malabo"),
    ("de la Guinée Conakry ?", ("Lomé", "Bisseau", "Malabo", "Conakry"), "Conakry"),
    ("de la Guinée Bissau ?", ("Accra", "Bissau", "Malabo", "Conakry"), "Bissau"),
    ("du Libéria ?", ("Libéria", "Libreville", "Monrovia", "Freetown"), "Monrovia"),
    ("du Cap Vert ?", ("Dakar", "Praia", "Malabo", "Faso"), "Praia"),
    ("de la Tanzanie ?", ("Dodoma", "Nairobi", "Malabo", "Antananarivo"), "Dodoma"),
    ("du Kenya ?", ("Eritré", "Pretoria", "Nairobi"), "Nairobi"),
    ("de la Libye ?", ("Yamoussokro", "Tripolie", "Malabo", "Libreville"), "Tripolie"),
    ("de la Tunisie ?", ("Tunis", "Praia", "Conakry", "Tunisia"), "Tunis"),
    ("de la Mauritanie ?", ("Nairobie", "Praia", "Nouakchott", "Maures"), "Nouakchott"),
    ("de l'Eswatini ?", ("Lilongwé", "Lobamba-Mbabane", "Caborone", "Tunisia"), "Lobamba-Mbabane"),
    ("du Malawi ?", ("Maseru", "Lilongwé", "Nouakchott", "Antananarivo"), "Lilongwé"),
    ("de la Mozambique ?", ("Namibie", "Lilongwé", "Nouakchott", "Maputo"), "Maputo"),
    ("de la Namibie ?", ("Maseru", "Lilongwé", "Nouakchott", "Windhoek"), "Windhoek"),
    ("de l'Erithrée ?", ("Eritré", "Asmara", "Malabo"), "Asmara"),

]
